### ISSUE TITLE
Binary Request: Version 1.14.6.19-stable or 1.14.6.18-stable For macOS 13.3.1 Intel CPU

### ISSUE THREAD

**Issue by dawnmy** [DEAKSoftware/Synergy-Binaries#25]
I would like to try the new version (1.14.6.19-stable or 1.14.6.18-stable) of Synergy on my MacBook pro with Intel CPU. Could you compile a DMG for it? Thank you for your efforts.

**Comment by myn** [comment]
That would be awesome!!!  Much appreciate it!

**Comment by thefat32** [comment]
Apparently the build for darwin x86_64 was disabled when arm64 build was added :( @DominikDeak was this intentional?

**Comment by thefat32** [comment]
I've just built it for myself. You can gather it from my repo https://github.com/thefat32/Synergy-Binaries/releases/edit/1.14.6.19-stable

**Comment by DominikDeak** [comment]
> Apparently the build for darwin x86_64 was disabled when arm64 build was added :( @DominikDeak was this intentional?

Ah no, it wasn't intentional. My crappy script just targets whatever architecture it is currently running on - and i mostly use M1s these days. I need to modify the script to build universal binaries (assuming if such build targets are even possible for the Synergy project). I just don't have time to do it. 

I do have an Intel mac though, I'll also run the scripts on that machine for the next release.

Also thanks for supplying a custom build.

**Comment by picchi-lucas** [comment]
Making an universal build should be possible using Qt [5.15.9](https://www.qt.io/blog/commercial-lts-qt-5.15.9-released) but we need a custom build as brew formulae is 5.15.8 and I don't think they will install universal binaries when they bump ot to 5.15.9.
An openssl universal build will be required too but I think it should be trivial to make using lipo.

I will try tu put some time on this. Having an universal build would be nice.

Thank you @DominikDeak for providing your builds.

It's the first time I needed to build Synergy myself.

**Comment by DominikDeak** [comment]
Release of latest stable version is up, including Intel mac builds: 
https://github.com/DEAKSoftware/Synergy-Binaries/releases/tag/1.14.6.19-stable
